services:
    main:
        build: .
        shm_size: '1gb'
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - ${XAUTHORITY}:/root/.Xauthority:ro

