services:
    main:
        container_name: alpine_firefox
        build: .
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - ${XAUTHORITY}:/root/.Xauthority:ro

