#!/bin/bash

rm -rf _build
mkdir -p _build/setup
cp -rL $(dirname $(readlink -f build))/scripts _build/setup
if [ -d setup ]; then
    cp -rL setup _build
fi
if [ -f docker-compose.yml ]; then
    docker-compose build
else
    image_name=$(basename `pwd`)
    build_opts="--tag $image_name:latest"
    if [ -f VERSION ]; then
        build_opts="$build_opts --tag $image_name:$(cat VERSION | sed 's/^[ \t]+//g' | sed 's/[ \t]$//g' | grep .)"
    fi
    docker build $build_opts .
fi

build_output_dir=`pwd`/_build/output
for cmd in /usr/local/bin/save_versions /usr/local/bin/save_sysinfo ; do
    if [ -f _build/setup/skel$cmd ] ; then
        mkdir -p $build_output_dir
        ./run $cmd
    fi
done
