#!/bin/bash

if [ $# -gt 0 ]; then
    additional_opts="--volume `pwd`/_build/output:/build_output"
fi

name=$(basename $(pwd))
docker run --rm --detach $(../resources/run/get_run_opts x11 git shm-1g project)  $additional_opts $name $@
