services:
        data_science:
                build: .
                environment:
                        - DISPLAY
                volumes:
                        - /tmp/.X11-unix:/tmp/.X11-unix:ro


