services:
    main:
        image:  jamesnetherton/docker-atom-editor
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /dev/shm:/dev/shm
            - ${HOME}:/home/atom
